version: '3'
volumes:
  data:
services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
    - 5432:5432
    volumes:
    - data:/var/lib/postgresql/data
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    links:
      - teste-postgres-compose
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@email.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - 80:80
    depends_on:
    - teste-postgres-compose
   